index:
    path: /
    controller: App\Controller\Calculator\CalculatorController::index
    methods: GET


resolve:
    path: /resolve
    controller: App\Controller\Calculator\CalculatorController::resolveExpression
    methods: POST